name: 'Maven GAV Extractor'
description: 'Extracts Maven groupId, artifactId and version from pom.xml'
branding:
  icon: 'bar-chart-2'  
  color: 'orange'
inputs:
  pom-location:
    description: 'Full path to pom.xml file'
    required: true
    default: ${{ github.workspace }}/pom.xml
outputs:
  group-id:
    description: Group Id
    value: ${{ steps.evaluate.outputs.group-id }}
  artifact-id:
    description: Artifact Id
    value: ${{ steps.evaluate.outputs.artifact-id }}
  version:
    description: Version
    value: ${{ steps.evaluate.outputs.version }}
  name:
    description: Name
    value: ${{ steps.evaluate.outputs.name }}
runs:
  using: 'composite'
  steps:
    - id: evaluate
      name: Extract GAV
      env:
        EVALUATE: org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate
      run: |
        VALUE=$(mvn -f ${{ inputs.pom-location }} $EVALUATE -Dexpression=project.groupId -q -DforceStdout)
        echo "group-id=$VALUE" >> $GITHUB_OUTPUT

        VALUE=$(mvn -f ${{ inputs.pom-location }} $EVALUATE -Dexpression=project.artifactId -q -DforceStdout)
        echo "artifact-id=$VALUE" >> $GITHUB_OUTPUT
        
        VALUE=$(mvn -f ${{ inputs.pom-location }} $EVALUATE -Dexpression=project.version -q -DforceStdout)
        echo "version=$VALUE" >> $GITHUB_OUTPUT
        
        VALUE=$(mvn -f ${{ inputs.pom-location }} $EVALUATE -Dexpression=project.name -q -DforceStdout)
        echo "name=$VALUE" >> $GITHUB_OUTPUT
      shell: bash
