name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Should extract GAV
    steps:
    - uses: actions/checkout@v3
    - name: Extract GAV
      id: extract
      uses: ./
      with:
        pom-location: ${{ github.workspace }}/.github/test-resources/pom.xml
    - name: Assert extracted GAV
      run: |
        echo ${{ steps.extract.outputs.group-id }}
        echo ${{ steps.extract.outputs.artifact-id }}
        echo ${{ steps.extract.outputs.version }}
        echo ${{ steps.extract.outputs.name }}
        
        wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh
        . assert.sh
        assert "echo ${{ steps.extract.outputs.group-id }}" "com.codingjam"
        assert "echo ${{ steps.extract.outputs.artifact-id }}" "github-action-poc"
        assert "echo ${{ steps.extract.outputs.version }}" "1.0.0-SNAPSHOT"
        assert "echo ${{ steps.extract.outputs.name }}" "github-action-poc"
        assert_end tests
      shell: bash